### ISSUE TITLE
Application group needs to exist

### ISSUE THREAD

**Issue by lazyatom** [tomafro/recap#1]
We could probably check to see if that's true. Or maybe even create it as part of `deploy:setup`?

**Comment by tomafro** [comment]
I think a user and group is needed for the app, i.e. `harmonia` and `harmonia`.  This could probably be made clearer in the documentation.  

I'm not sure a specific `application` group is needed, only that the deploying user is a member of the `harmonia` (or whatever) group and has write access to `/var/apps` and `/var/apps/harmonia`, but maybe that's not what you meant?

**Comment by tomafro** [comment]
I've added preflight checks to ensure that the application user and group both exist (e.g. `harmonia` and `harmonia`).  I don't think a generic application group is needed, but could be persuaded otherwise.
