### ISSUE TITLE
Maintenance Page

### ISSUE THREAD

**Issue by tf** [tomafro/recap#102]
Would there be interest in a pull requests adding tasks to control the display of a maintenance page (i.e. `web:disable` etc)? I would say it's a quite common need. Moreover, libraries like [capistrano/mainentance](https://github.com/capistrano/maintenance) often come with assumptions about `shared_path` which do not make sense in the context of recap.

**Comment by tomafro** [comment]
I tend not to use maintenance pages (much prefer zero-downtime deployment), but if you think there's some value why not create a `recap-maintenance` repository with the appropriate tasks? If there's anything in recap that makes this difficult, let me know and I'll take a look.
