### ISSUE TITLE
Add cap env:unset <VARIABLE> to remove an env variable

### ISSUE THREAD

**Issue by tomafro** [tomafro/recap#12]
Currently you can do `cap env:set PASSWORD=` to unset something, but that seems very very clunky.  I'd like to remove that behaviour, and replace it with a dedicated `cap env:unset PASSWORD` command.

**Comment by lazyatom** [comment]
The problem we hit doing this is that Capistrano does seem to have some expectation about its args; running

```
cap env:unset BLAH
```

will eventually try to invoke a task called `BLAH`.

There might be ways around this, but I suspect they'll involve poking deeper into Capistrano's guts; possibly even into `OptionParser`'s.

**Comment by lazyatom** [comment]
Here's my attempt (still exhibiting the above problem): https://github.com/lazyatom/tomafro-deploy/commit/4e35709e466819eb641734b72851e2c5e70d805c

**Comment by tomafro** [comment]
Looks like it will be too much hassle to get `unset` working.  Really don't want to mess with capistrano internals.  For now I think it's best to leave it with the clunky `cap env:set PASSWORD=`
