### ISSUE TITLE
Think of a better name for the project

### ISSUE THREAD

**Issue by tomafro** [tomafro/recap#14]
`tomafro-deploy` is massively egotistical.  I generally use `tomafro` as a prefix for stuff that is meant just for me.  If other people start using these recipes, I'd like to come up with a better name (and probably move the project over to freerange).

**Comment by lazyatom** [comment]
Do you want whimsy ("vlad") or pragmatism ("git-deploy")?

**Comment by lazyatom** [comment]
If we start to feel this has legs, I'd quite happily abandon our existing `freerange-deploy` and give that name to this. Does that help?

**Comment by tomafro** [comment]
If I can't come up with a better name, abandoning `freerange-deploy` might be the way to go.

**Comment by tomafro** [comment]
I'm going with `recap`
