### ISSUE TITLE
.env values not loaded for non-interactive shells

### ISSUE THREAD

**Issue by lazyatom** [tomafro/recap#15]
``` shell
james@li152-44:~$ whoami
james
james@li152-44:~$ cat /home/sauron/.env
PASSWORD=blahblah
PATH=/var/rubies/1.9.2-p290/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
RAILS_ENV=production
USER_NAME=blah
james@li152-44:~$ cat /home/sauron/.profile 
if [ -s "$HOME/.env" ]; then export $(cat $HOME/.env); fi
james@li152-44:~$ sudo su - sauron -c echo $RAILS_ENV

james@li152-44:~$
```

This seems to also mean that running applications using foreman don't get these environment variables.

**Comment by tomafro** [comment]
Can you try `sudo su - sauron -c env`?

On my test VM I get:

```
$ cat /home/blanche/.env
PASSWORD=secret

$ sudo su - blanche -c env
USER=blanche
LANGUAGE=en_US:
HOME=/home/blanche
LOGNAME=blanche
TERM=xterm-color
PATH=/home/blanche/.rbenv/bin:/home/blanche/.rbenv/shims:/home/blanche/bin:/usr/local/bin:/usr/bin:/bin
LANG=en_US.UTF-8
SHELL=/bin/sh
PWD=/home/blanche
PASSWORD=secret
```

**Comment by tomafro** [comment]
In fact, if I do the `echo $VAR` approach I never get any response.

```
$ sudo su - blanche -c echo $PATH

$ sudo su - blanche -c echo $HOME

$
```

Quoting the command works though:

```
$ sudo su - blanche -c 'echo $PATH'
/home/blanche/.rbenv/bin:/home/blanche/.rbenv/shims:/home/blanche/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
```

**Comment by tomafro** [comment]
Closing for now.  Please reopen if you think this is still a problem.

**Comment by lazyatom** [comment]
You're right - I'd tried double-quoting the command, which didn't work, but I didn't realise that single-quoting would be different. And env reveals that the variables are indeed set.

Now to figure out why they weren't being picked up by the process that was actually started using `sudo su`....

**Comment by tomafro** [comment]
FYI, I have a rails app, https://github.com/tomafro/blanche, that I've been using for deployment.  You might find it useful.  Its only controller shows the env.
