### ISSUE TITLE
Environment variables with spaces break export

### ISSUE THREAD

**Issue by lazyatom** [tomafro/recap#23]
We get the "<x> not a valid identifier" error as seen below when running `export` on the output of `cat env`

``` shell
bash-3.2$ cat env
JAZZ=handle 
MONKEY=ape 
LIST="this, that" 
bash-3.2$ export JAZZ=blah MONKEY=baboon LIST="apples, pears"
bash-3.2$ echo $LIST
apples, pears
bash-3.2$ export JAZZ=smooth \
> MONKEY=gorilla \
> LIST="cats, dogs"
bash-3.2$ echo $LIST
cats, dogs
bash-3.2$ export $(cat env)
bash: export: `that"': not a valid identifier
```

**Comment by lazyatom** [comment]
I also tried changing `.profile` to just invoke `$(cat $HOME/.env)` without the export, and add `export` to the start of each line in `.env`, with the same results.

**Comment by tomafro** [comment]
This should be fixed now, though the solution seems like a bit of a hack.  The `.env` file is read, and a new file generated adding the prefix `export` to each line.  This new temporary file is then sourced.

As well as adding strings with spaces, this also allows reference to other variables, e.g. OPTIONS_PATH=$HOME/options

**Comment by lazyatom** [comment]
Looks good to me; I like the idea of the .recap file too.
