### ISSUE TITLE
`current_path` and `release_path` aren't valid

### ISSUE THREAD

**Issue by lazyatom** [tomafro/recap#3]
Some tools (like `whenever`) expect the capistrano default directories to exist; to be a nice neighbour, we probably ought to ensure that we cajole such tools into running in the right place.

One approach might be to redefine the variables as methods:

```
def current_path
  deploy_to
end
def release_path
  deploy_to
end
```

**Comment by lazyatom** [comment]
... or even just

```
set :current_path, deploy_to
set :release_path, deploy_to
```

**Comment by tomafro** [comment]
Even with these paths, the whenever capistrano tasks won't rollback correctly.  I'm not sure the wisdom of trying too hard to to support other recipes based on the original capistrano stuff.  Maybe a `compatibility` recipe could add these paths, and only be included when needed.

**Comment by lazyatom** [comment]
Considering "whenever" directly is probably a red herring; I think that there might still be some merit in having "current_path" and/or "releases_path" point to the actual directory where code is though. Probably more the former("current_path") than the latter.

**Comment by tomafro** [comment]
Didn't mean to close this, BTW.  Got to stop clicking 'comment & close' !

**Comment by tomafro** [comment]
I've added current path to a compatibility recipe.  Other stuff can be added there if required.

**Comment by lazyatom** [comment]
Cool; I think that's a good approach.

**Comment by lulalala** [comment]
I tried using this by doing `require 'recap/support/compatibility'` in my Capfile, but it complains that _cset method is absent. Is this the proper way to include compatibility module?
