### ISSUE TITLE
`recap setup` displays git error if run outside of a git repository

### ISSUE THREAD

**Issue by chrisroos** [tomafro/recap#44]
To recreate:

```
$ rails new tmp-recap-test
$ cd tmp-recap-test
$ echo "gem 'recap'" >> Gemfile
$ bundle install
$ bundle exec recap setup
fatal: Not a git repository (or any of the parent directories): .git
```

It would appear that the Capfile is created successfully (albeit with an empty repository string) so it might be enough to trap the fatal git error and print a warning that we couldn't set the repository automatically.

**Comment by floehopper** [comment]
I've added what I think was a missing `cd tmp-recap-test` to the steps to recreate.

**Comment by floehopper** [comment]
This should be fixed in #51. The new behaviour is to print a warning to stderr :-

```
Unable to determine git repository.  Setting to <unknown>.
```

And to create the `Capfile` with the repository set as follows :-

```
set :repository, '<unknown>'
```

**Comment by floehopper** [comment]
@chrisroos can you see whether this is fixed? Thanks.

**Comment by lazyatom** [comment]
I'll check this.

**Comment by lazyatom** [comment]
Looks good to me.
