### ISSUE TITLE
Are non-git-tracked files and symlinks left alone?

### ISSUE THREAD

**Issue by airblade** [tomafro/recap#6]
Let's say my app lets people upload photos to a directory symlinked from my Rails app's public directory.  Will all the `git reset --hard` shenanigans leave my symlinks intact?

(I really should just test this myself but I thought you could just tell me yes/no ;)

**Comment by tomafro** [comment]
I don't think the `git reset --hard` stuff will touches symlinks, no.  If you have (or add) files or folders in your repository with the same path as your symlinks, then I imagine it would cause problems, but proving you don't do that you should have no troubles.

BTW, this project is still pretty experimental and unstable at the moment.  I'll announce it if and when we start using it in anger more.  (And I'll move the version on from 0.0.1!)
