### ISSUE TITLE
Doc CSS

### ISSUE THREAD

**Issue by crofty** [tomafro/recap#73]
Not sure which repo your docs are located in but they need a CSS update, the stylesheet link to the Docco CSS is broken - http://gofreerange.com/recap/docs/recap.html

**Comment by lazyatom** [comment]
Cheers @crofty - it's because Docco changed it's CSS without bearing in mind that there were other tools (Rocco) using it (see https://github.com/rtomayko/rocco/issues/98). I've fixed it temporarily while we have a think about a better solution.

**Comment by tomafro** [comment]
I think this is good enough for the time being.  If rocco fix this upstream we can revert our change.
