### ISSUE TITLE
cap deploy:setup stops at username for github

### ISSUE THREAD

**Issue by henry74** [tomafro/recap#84]
I've had a few hiccups trying to get this working.  Not sure if I'm doing something different than others.

I had to install ruby separately on the new account since I use rbenv and had to install ruby for the application user in order to get bundler working.

Now I'm trying to do the deployment to the server as a test.  The scripts seems to have created the global username and email for git config, but the cap deploy:setup step is getting stuck here:

```
  * executing "cd /home/myApp/app && umask 002 && sg myApp -c \"git clone https://github.com/henry74/myApp.git .\""
    servers: ["myserver.com"]
    [admin@myserver.com] executing command
 ** [out :: admin@myserver.com] Cloning into '.'...
 ** [out :: admin@myserver.com] 
 ** [out :: admin@myserver.com] Username for 'https://github.com':
```

Any suggestions?

**Comment by tomafro** [comment]
You should set your `Capfile` to use your ssh clone url, not the https url.
 i.e: `git@github.com:freerange/recap.git` rather than `
https://github.com/freerange/recap.git` (but for your repository, not
recap!).

**Comment by henry74** [comment]
Thanks - that worked.  The clone url was originally generated by recap so didn't think it needed to be changed.

**Comment by tomafro** [comment]
recap just takes whichever url you originally cloned from.  Perhaps it should be a little bit cleverer in this respect.

**Comment by henry74** [comment]
Great setup you created, nonetheless. I think github pushed folks to use https by default so this may happen to most folks picking this up now.
