### ISSUE TITLE
load seeds on rails:db:load_schema

### ISSUE THREAD

**Issue by scambra** [tomafro/recap#89]
Currently run db:create db:schema:load, could it run db:seed too? Or only run db:setup which runs db:create db:schema:load and db:seed

Also, IIRC db:schema:load depends on db:create, so db:create could be deleted from rails:db:load_schema

**Comment by tomafro** [comment]
I'm not convinced that `db:seed` should be run on production machines.  It depends what you use it for.  I know many projects I've worked on have used it to create seed data for developers, not intended for production.

If you want this behaviour, you can always add:

```
task :seed_db do
  as_app_once 'rake db:seed'
end

after 'rails:db:load_schema', 'seed_db'
```

to your `Capfile`
